# -*- coding: utf-8 -*-
"""MySentimentAnalyzer_Gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNYEBWCcbHDjGfcWOkWqf1T9DlJ3_lIw
"""

!pip install gradio

import gradio as gr
from transformers import pipeline

sentiment = pipeline("sentiment-analysis")

def findSentiment(input):
  return sentiment(input)

result = findSentiment("You are jokingly good!")

print(result)

iface = gr.Interface(fn=findSentiment,
                     inputs="text",
                     outputs=["text"],title="MY Sentiment Analyzer",
                     theme="darkhuggingface"
                     )

iface.launch()

